### ISSUE TITLE
Ability to add Mentors to Batches

### ISSUE THREAD

**Issue by binnyva** [makeadiff/Madnet#92]
## Summary
We should be able to assign mentors to batches. Multiple mentors per batch if need be.

## Page/Module
Shelter > Batches > Edit Batch - Eg. <https://makeadiff.in/madnet/#/shelters/244/projects/4/batches/3846>

### API
POST /batches/{batch_id}/mentors - [Documentation](http://makeadiff.in/api/api/swagger/doc.html#tag/mentor%2Fpaths%2F~1batches~1%7Bbatch_id%7D~1mentors%2Fpost)

**Comment by jesusj0o** [comment]
Hello there! I would like to work on this as well!

**Comment by craterkamath** [comment]
I will be working on this issue! Thanks :D

**Comment by craterkamath** [comment]
Opened #116 for the enhancement. @binnyva  Can you please take a look at this and review?

**Comment by craterkamath** [comment]
I have not added a dedicated section "Mentor Assignments" per say (just like "Teacher Assignments") in the /shelters/XXX. But it can be easily added since /shelters/XXX/batches/0/ directs to the over page: currently the "Add Mentors" button is disabled on that page. But this would need us to add an additional page(just like in the "Teacher Assignments" case) or we can add a button per item in the overview list (just like in the "Class Sections") case. Happy to discuss further on this since the changes can come in a different patchset.

**Comment by binnyva** [comment]
Works perfectly! Thanks :-D
